### ISSUE TITLE
bad array subscript when running inside ignored directory

### ISSUE THREAD

**Issue by jhasse** [gerph/ls-with-git-status#2]
When running lsg inside a gitignored directory I'm getting:

```
lsg: line 605: git_status[$name]: bad array subscript
```

This is with Git 2.26.2 and Bash 5.0.17 on Linux.

**Comment by gerph** [comment]
Reproduced here. Will investigate after work. Thanks!

**Comment by gerph** [comment]
I've just pushed a new version of the tool which I think should fix the issue.
Hope that fixes it for you?

**Comment by jhasse** [comment]
Yes, thank you :)

Btw: lsg works on Windows with MSYS2, too.
