### ISSUE TITLE
long listing by default

### ISSUE THREAD

**Issue by klaernie** [gerph/ls-with-git-status#3]
I just discovered this neat utility, but immediately wanted to change it's default to listing in the long format.

My local option is of cause the simplest - setting the initialization of `$ls_switches` to `( "-l" )`, but it would be nice if that would be a similar to ls a global `$LSG_OPTIONS` environment variable that gets processed as a default.

**Comment by gerph** [comment]
That seems like a good idea.

**Comment by gerph** [comment]
Should be added in the latest version, thanks for the suggestion!
Let me know if there's any other issues.

**Comment by klaernie** [comment]
thanks, works a treat!
